# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-21 03:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_fund_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='content',
            field=models.CharField(default=b'SOME STRING', max_length=140),
        ),
        migrations.AddField(
            model_name='fund',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='fund',
            name='expenses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fund',
            name='profit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fund',
            name='user_story',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='user_task',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
