# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-21 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_auto_20190621_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='content',
            field=models.CharField(default=b' ', max_length=140),
        ),
    ]
