# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-21 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_auto_20190621_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='user_story',
            new_name='works',
        ),
    ]
